# Each new term in the Fibonacci sequence is generated by
# adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence
# whose values do not exceed four million, find the sum of the
# even-valued terms


##variables:
oldNumb = 1
newNumb = 2
totalNumb = 0
# 1-set the max limit
maxLimit = 60

# 1-Get the sum of even number, need to start with 2 first in order for it to
# work
sumEvenNumb = 0

# 3b- create a new variable to capture the remainder
remainder = 0

# Codes
# 1-Get the the structure of Fibonacci first

while (totalNumb < maxLimit):
    totalNumb = oldNumb + newNumb
    print(totalNumb)

    # 3- Need to aggregate the even number, use the remainder to see if
    # 3- total number / 2 =0
    # if((totalNumb%2)==0)
    # sumEvenNumb=sumEvenNumb+totalNumb
    # print (sumEvenNum)

    # 3a-testing remainder operation
    # print (totalNumb%2)--output is 1,1,0 with maxlimit =0
    # Question: why is it not working with the above IF statment???
    # Option- create a new variable- "remiander" to capture the reaminder
    # and do a comparison, but the above should work.....no?
    # 3b-
    #remainder = totalNumb % 2
    # 3b1- test that the remainder does print...works"
    # print(remainder)
    # 3b2- now use in the if statement
    # if((totalNumb%2)==0).....FAILED
    # sumEvenNumb=sumEvenNumb+totalNumb
    # print (remainder==0)...Works....what is the difference

    # ANSWER, forgot the ":" at the of the if statement
    if ((totalNumb % 2) == 0):
        sumEvenNumb = sumEvenNumb + totalNumb
        # print ("Even Numbers: ")
        # how to print a string and variable together in one line?

        # ANSWER:...moving to the if statement
        # print (sumEvenNumb)

    # 1-update the values of old and new number
    oldNumb = newNumb
    newNumb = totalNumb
    # 2-Need a checker to make sure that it does not exceed the max limit
    if ((newNumb + oldNumb) > maxLimit):
        print("Even Numbers: ")
        print(sumEvenNumb)
        break